export const layout65 = [
  [
    {
      label: "",
      subLabel: "esc",
      legend: "",
      code: "Escape",
      color: { r: 235, g: 234, b: 231 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "1",
      subLabel: "!",
      legend: "ぬ",
      code: "Digit1",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "2",
      subLabel: "@",
      legend: "ふ",
      code: "Digit2",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "3",
      subLabel: "#",
      legend: "あ",
      code: "Digit3",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "4",
      subLabel: "$",
      legend: "う",
      code: "Digit4",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "5",
      subLabel: "%",
      legend: "え",
      code: "Digit5",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "6",
      subLabel: "^",
      legend: "お",
      code: "Digit6",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "7",
      subLabel: "&",
      legend: "や",
      code: "Digit7",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "8",
      subLabel: "*",
      legend: "ゆ",
      code: "Digit8",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "9",
      subLabel: "(",
      legend: "よ",
      code: "Digit9",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "0",
      subLabel: ")",
      legend: "わ",
      code: "Digit0",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "-",
      subLabel: "_",
      legend: "ほ",
      code: "Minus",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "=",
      subLabel: "+",
      legend: "へ",
      code: "Equal",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "backspace",
      subLabel: "",
      legend: "",
      code: "Backspace",
      color: { r: 235, g: 234, b: 231 },
      sound: "backspace",
      sounUp: "backspace-up",
      width: 2,
    },
    {
      label: "pause",
      subLabel: "",
      legend: "",
      code: "Pause",
      color: { r: 235, g: 234, b: 231 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
  ],
  [
    {
      label: "tab",
      subLabel: "",
      legend: "",
      code: "Tab",
      color: { r: 235, g: 234, b: 231 },
      sound: "tab",
      soundUp: "tab-up",
      width: 1.5,
    },
    {
      label: "q",
      subLabel: "",
      legend: "た",
      code: "KeyQ",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "w",
      subLabel: "",
      legend: "て",
      code: "KeyW",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "e",
      subLabel: "",
      legend: "い",
      code: "KeyE",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "r",
      subLabel: "",
      legend: "す",
      code: "KeyR",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "t",
      subLabel: "",
      legend: "か",
      code: "KeyT",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "y",
      subLabel: "",
      legend: "ん",
      code: "KeyY",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "u",
      subLabel: "",
      legend: "な",
      code: "KeyU",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "i",
      subLabel: "",
      legend: "に",
      code: "KeyI",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "o",
      subLabel: "",
      legend: "ら",
      code: "KeyO",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "p",
      subLabel: "",
      legend: "せ",
      code: "KeyP",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "[",
      subLabel: "{",
      legend: "゛",
      code: "BracketLeft",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "]",
      subLabel: "}",
      legend: "゜",
      code: "BracketRight",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "\\",
      subLabel: "|",
      legend: "む",
      code: "Backslash",
      color: { r: 255, g: 255, b: 255 },
      sound: "backslash",
      soundUp: "backslash-up",
      width: 1.5,
    },
    {
      label: "del",
      subLabel: "",
      legend: "",
      code: "Delete",
      color: { r: 235, g: 234, b: 231 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
  ],
  [
    {
      label: "capslock",
      subLabel: "",
      legend: "",
      code: "CapsLock",
      color: { r: 235, g: 234, b: 231 },
      sound: "capslock",
      soundUp: "capslock-up",
      width: 1.7,
    },
    {
      label: "a",
      subLabel: "",
      legend: "ち",
      code: "KeyA",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "s",
      subLabel: "",
      legend: "と",
      code: "KeyS",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "d",
      subLabel: "",
      legend: "し",
      code: "KeyD",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "f",
      subLabel: "",
      legend: "は",
      code: "KeyF",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "g",
      subLabel: "",
      legend: "き",
      code: "KeyG",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "h",
      subLabel: "",
      legend: "く",
      code: "KeyH",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "j",
      subLabel: "",
      legend: "ま",
      code: "KeyJ",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "k",
      subLabel: "",
      legend: "の",
      code: "KeyK",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "l",
      subLabel: "",
      legend: "り",
      code: "KeyL",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: ";",
      subLabel: ":",
      legend: "れ",
      code: "Semicolon",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "'",
      subLabel: '"',
      legend: "け",
      code: "Quote",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "enter ツ",
      subLabel: "",
      legend: "",
      code: "Enter",
      color: { r: 64, g: 62, b: 62 },
      sound: "enter",
      soundUp: "enter-up",
      width: 2.3,
    },
    {
      label: "pgup",
      subLabel: "",
      legend: "",
      code: "PageUp",
      color: { r: 235, g: 234, b: 231 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
  ],
  [
    {
      label: "Shift",
      subLabel: "",
      legend: "",
      code: "ShiftLeft",
      color: { r: 235, g: 234, b: 231 },
      sound: "shiftleft",
      soundUp: "shiftleft-up",
      width: 2,
    },
    {
      label: "z",
      subLabel: "",
      legend: "つ",
      code: "KeyZ",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "x",
      subLabel: "",
      legend: "さ",
      code: "KeyX",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "c",
      subLabel: "",
      legend: "そ",
      code: "KeyC",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "v",
      subLabel: "",
      legend: "ひ",
      code: "KeyV",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "b",
      subLabel: "",
      legend: "こ",
      code: "KeyB",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "n",
      subLabel: "",
      legend: "み",
      code: "KeyN",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "m",
      subLabel: "",
      legend: "も",
      code: "KeyM",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: ",",
      subLabel: "<",
      legend: "ね",
      code: "Comma",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: ".",
      subLabel: ">",
      legend: "る",
      code: "Period",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "/",
      subLabel: "?",
      legend: "め",
      code: "Slash",
      color: { r: 255, g: 255, b: 255 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "Shift",
      subLabel: "",
      legend: "",
      code: "ShiftRight",
      color: { r: 235, g: 234, b: 231 },
      sound: "shiftright",
      soundUp: "shiftright-up",
      width: 2,
    },
    {
      label: "↑",
      subLabel: "",
      legend: "",
      code: "ArrowUp",
      color: { r: 64, g: 62, b: 62 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "pgdn",
      subLabel: "",
      legend: "",
      code: "PageDown",
      color: { r: 235, g: 234, b: 231 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
  ],
  [
    {
      label: "ctrl",
      subLabel: "",
      legend: "",
      code: "ControlLeft",
      color: { r: 235, g: 234, b: 231 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "win",
      subLabel: "",
      legend: "",
      code: "MetaLeft",
      color: { r: 235, g: 234, b: 231 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "alt",
      subLabel: "",
      legend: "",
      code: "AltLeft",
      color: { r: 235, g: 234, b: 231 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "",
      subLabel: "",
      legend: " ",
      code: "Space",
      color: { r: 64, g: 62, b: 62 },
      sound: "space",
      soundUp: "space-up",
      width: 7,
    },
    {
      label: "alt",
      subLabel: "",
      legend: "",
      code: "AltRight",
      color: { r: 235, g: 234, b: 231 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "func",
      subLabel: "",
      legend: "",
      code: "Fn",
      color: { r: 235, g: 234, b: 231 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "ctrl",
      subLabel: "",
      legend: "",
      code: "ControlRight",
      color: { r: 235, g: 234, b: 231 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "←",
      subLabel: "",
      legend: "",
      code: "ArrowLeft",
      color: { r: 64, g: 62, b: 62 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "↓",
      subLabel: "",
      legend: "",
      code: "ArrowDown",
      color: { r: 64, g: 62, b: 62 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
    {
      label: "→",
      subLabel: "",
      legend: "",
      code: "ArrowRight",
      color: { r: 64, g: 62, b: 62 },
      sound: "regular",
      soundUp: "regular-up",
      width: 1,
    },
  ],
];
